# Metadata syntax: <https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions>

name: Install Podman
description: Installs a fresh Podman version in your GitHub Actions workflow

inputs:
  kind:
    description: The version kind
    default: 'testing' # or 'unstable'
  qemu:
    description: Install QEMU
    default: 'false' # or 'true'
  cache-salt:
    description: The cache salt
    default: 'v1'

runs:
  using: composite
  steps: # manual: <https://podman.io/docs/installation#debian>
    - if: ${{ inputs.kind == 'testing' }}
      shell: bash
      run: |
        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null

    - if: ${{ inputs.kind == 'testing' }}
      shell: bash
      run: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

    - if: ${{ inputs.kind == 'unstable' }}
      shell: bash
      run: |
        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null

    - if: ${{ inputs.kind == 'unstable' }}
      shell: bash
      run: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

    - shell: bash
      run: sudo apt-get -q update

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: aardvark-dns conmon containers-common criu crun libnet1 libprotobuf-c1 libprotobuf23 netavark podman-gvproxy python3-protobuf conmon crun podman
        version: ${{ inputs.cache-salt }}

    - shell: bash
      run: sudo apt-get -yq install podman

    - if: ${{ inputs.qemu == 'true' }}
      shell: bash
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

branding:
  icon: download
  color: purple
